spring.application.name=snipLink

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/urlshortener}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update

# Redis
spring.data.redis.url=${SPRING_DATA_REDIS_URL:redis://localhost:6379}

# Enable @Async
spring.task.execution.pool.core-size=5